### ISSUE TITLE
Results page has errors

### ISSUE THREAD

**Issue by teveritt** [appliedrelevance/design-assistant#26] opened 2022-03-24 15:05 UTC
![Screenshot 2022-03-24 105052](https://user-images.githubusercontent.com/65302023/159946769-fad2cf18-a434-4baa-ae66-ec99dcaaa9e6.png)

**Comment by aaronlugo** [comment] 2022-03-25 03:03
Can you provide more details? I cannot reproduce it

**Comment by teveritt** [comment] 2022-03-25 15:40
This is happening for me on Chrome/Edge but not Firefox. Not sure if it's relevant, but this appears in the console when the results page is refreshed:
![Screenshot 2022-03-25 113405](https://user-images.githubusercontent.com/65302023/160152244-5f818549-76c8-4c44-9c43-09b1ec70c978.png)

![Screenshot 2022-03-25 113515](https://user-images.githubusercontent.com/65302023/160152519-cbe7bae2-fcfd-4bcf-bdd6-247651882a7e.png)

Chrome Version 99.0.4844.82

**Comment by aaronlugo** [comment] 2022-03-25 16:29
I cannot reproduce this

**Comment by geverit4** [comment] 2022-04-14 21:36
Closing.  Not reproducible.

**Closed by geverit4** 2022-04-14 21:36 UTC
Labels: bug
